# Site
name: "Donutlearning"
description: To attain knowledge, add things everyday. To attain wisdom, remove things everyday.

meta_description: "Jekyll template, Medium styled, free for bloggers."
logo: 'assets/images/logo.png'
brain: 'assets/images/brain.jpg'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-131511394-1'
disqus: ''
mailchimp-list: ''
hideMainHeading: false

# Authors
authors:
  shreyas:
    name: Shreyas
    display_name: Shreyas
    email: shreyas.rh9@gmail.com
    description: "Author of donutlearning."
  
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-tactile